# Generated by Django 4.0.3 on 2022-03-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('use_middlename', models.BooleanField(default=False)),
                ('use_second_surname', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
