# Generated by Django 4.0.3 on 2022-03-29 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0003_medicalrecord_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avisos.member'),
        ),
    ]
