# Generated by Django 4.0.3 on 2022-03-29 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0004_alter_medicalrecord_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cars', models.ManyToManyField(blank=True, to='avisos.car')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.plancategory')),
                ('emergency_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='avisos.member')),
                ('members', models.ManyToManyField(blank=True, to='avisos.member')),
            ],
        ),
    ]
