# Generated by Django 4.0.3 on 2022-04-10 19:51

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_plancategory_shortplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='member',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avisos.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
