# Generated by Django 4.0.3 on 2022-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0007_alter_medicalrecord_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
