# Generated by Django 4.0.3 on 2022-04-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0008_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortplan',
            old_name='members',
            new_name='participants',
        ),
        migrations.RemoveField(
            model_name='shortplan',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='shortplan',
            name='cau_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_contact', to='avisos.member'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
        ),
    ]
