# Generated by Django 4.0.3 on 2022-04-11 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0009_rename_members_shortplan_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado'), (2, 'Activo'), (3, 'Retrasado'), (4, 'Llegado'), (5, 'Cancelado')], default=0)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cars', models.ManyToManyField(blank=True, to='avisos.car')),
            ],
        ),
        migrations.RenameModel(
            old_name='PlanCategory',
            new_name='NoticeCategory',
        ),
        migrations.DeleteModel(
            name='ShortPlan',
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.noticecategory'),
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='cau_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_contact', to='avisos.member'),
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='participants',
            field=models.ManyToManyField(blank=True, to='avisos.member'),
        ),
    ]
