# Generated by Django 4.0.3 on 2022-04-13 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0010_shortnotice_rename_plancategory_noticecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='title',
            field=models.CharField(default='wena', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
