# Generated by Django 4.0.3 on 2022-04-13 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0011_shortnotice_created_at_shortnotice_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnotice',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='max_end_date',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='BaseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado'), (2, 'Activo'), (3, 'Retrasado'), (4, 'Llegado'), (5, 'Cancelado')], default=0)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(blank=True, to='avisos.car')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.noticecategory')),
                ('participants', models.ManyToManyField(blank=True, to='avisos.member')),
            ],
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='basenotice_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avisos.basenotice'),
            preserve_default=False,
        ),
    ]
