# Generated by Django 4.0.3 on 2022-04-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0012_remove_shortnotice_cars_remove_shortnotice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnotice',
            name='cau_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_contact', to='avisos.member'),
        ),
    ]
