# Generated by Django 4.0.3 on 2022-04-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0014_car_created_at_car_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnotice',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shortnotice',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
