# Generated by Django 4.0.3 on 2022-04-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0015_alter_shortnotice_location_alter_shortnotice_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnotice',
            name='cau_contact',
        ),
        migrations.AddField(
            model_name='basenotice',
            name='cau_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_contact', to='avisos.member'),
        ),
    ]
