# Generated by Django 4.0.3 on 2022-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0016_remove_shortnotice_cau_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='WENA', max_length=100),
            preserve_default=False,
        ),
    ]
