# Generated by Django 4.0.3 on 2022-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0018_medicalrecord_no_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='main_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('main_contact', True)), fields=('main_contact',), name='unique_main_contact'),
        ),
    ]
