# Generated by Django 4.0.3 on 2022-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0019_emergencycontact_main_contact_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emergencycontact',
            name='unique_main_contact',
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('main_contact', True)), fields=('main_contact', 'member'), name='unique_main_contact'),
        ),
    ]
