# Generated by Django 4.0.3 on 2022-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0021_emergencycontact_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basenotice',
            name='title',
        ),
        migrations.AlterField(
            model_name='shortnotice',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shortnotice',
            name='route',
            field=models.CharField(max_length=100),
        ),
    ]
