# Generated by Django 4.0.3 on 2022-04-23 21:32

import avisos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0024_alter_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images', validators=[avisos.models.file_size]),
        ),
    ]
