# Generated by Django 4.0.3 on 2022-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0025_rename_risks_friend_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='include_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
