# Generated by Django 4.0.3 on 2022-04-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0025_alter_member_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='alias',
        ),
    ]
