# Generated by Django 4.0.3 on 2022-08-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0026_basenotice_include_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
