# Generated by Django 4.0.3 on 2022-04-25 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0026_rename_name_car_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNoticeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sendto_caucontacts', models.BooleanField(default=True)),
                ('sendto_participants', models.BooleanField(default=True)),
                ('sendto_comisionseguridad', models.BooleanField(default=True)),
                ('sendto_directiva', models.BooleanField(default=True)),
                ('sendto_cau', models.BooleanField(default=False)),
                ('sendto_emergencycontacts', models.BooleanField(default=False)),
                ('sendto_other_emails', models.TextField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.shortnotice')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
