# Generated by Django 4.0.3 on 2022-04-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0027_sendnoticeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basenotice',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='avisos.member'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SendNoticeInfo',
        ),
        migrations.AddField(
            model_name='basenotice',
            name='email_recipients',
            field=models.ManyToManyField(blank=True, related_name='email_recipients', to='avisos.emailrecipient'),
        ),
    ]
