# Generated by Django 4.0.3 on 2022-05-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0028_emailrecipient_basenotice_sent_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, through='avisos.CommitteeMember', to='avisos.member'),
        ),
        migrations.CreateModel(
            name='ClubBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('clubboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.clubboard')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubboard',
            name='members',
            field=models.ManyToManyField(blank=True, through='avisos.ClubBoardMember', to='avisos.member'),
        ),
    ]
